# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daaf864303ee751396029ec125c06a0f2cc60c21e76ed14eaa9303681fc23582855e648a3fcdbb02d09a433c39509f244c6c4a7f73be062e0b1de04025bdc5c6

test:
  secret_key_base: 8219934f5ef1193cf59a1655765955a891c23286660f88abe0b60bfb4db01a0388be88b9737edadacf0d5fef1538b80838c8106c7a35d17b96e130db1169588f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
